# Configuration for benchmarking recent frontier models via OpenRouter
models:
  - model: openai/gpt-5
    label: gpt5-low
    params:
      reasoning_effort: low

  - model: openai/gpt-5
    label: gpt5-medium
    params:
      reasoning_effort: medium

  - model: openai/gpt-5
    label: gpt5-high
    params:
      reasoning_effort: high

  # xAI Grok-4
  - model: x-ai/grok-4
    label: grok-4

  # Anthropic Claude 4 (Sonnet / Opus)
  - model: anthropic/claude-sonnet-4
    label: claude-4-sonnet

  - model: anthropic/claude-opus-4.1
    label: claude-4-opus

  # Qwen3 Instruct sizes
  - model: qwen/qwen3-8b:free
    label: qwen3-8b

  - model: qwen/qwen3-30b-a3b-instruct-2507
    label: qwen3-30b-a3b

  - model: qwen/qwen3-235b-a22b-2507
    label: qwen3-235b-a22b

  # OpenAI-OSS open-weight models
  - model: openai/gpt-oss-20b
    label: gpt-oss-20b

  - model: openai/gpt-oss-120b
    label: gpt-oss-120b